services:
  nginx:
    image: nginx:local
    environment:
      PHPFPM_HOST: php
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
    ports:
      - "8080:80"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

